name: Spring Boot CI/CD with Direct Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 创建项目目录（如果不存在）
            mkdir -p ~/springboot-project
            cd ~/springboot-project
            
            # 拉取最新代码
            if [ ! -d ".git" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }} .
            else
              git fetch origin
              git reset --hard origin/main
            fi
            
            # 设置Java环境
            # 安装必要的软件
            sudo yum update -y
            sudo yum install -y git java-17-openjdk-devel maven
            
            # 构建项目
            mvn clean package -DskipTests
            
            # 构建Docker镜像
            docker build -t springboot-app .
            
            # 停止并删除旧容器
            docker stop springboot-app || true
            docker rm springboot-app || true
            
            # 运行新容器
            docker run -d --name springboot-app -p 8080:8080 springboot-app    
