name: Deploy Spring Boot Application

# 这里仅需要PR合并时执行CI
on:
  pull_request:
    branches:
      - master
  # 支持手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 提取短哈希并设置为环境变量
    - name: Set short SHA
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-6)" >> $GITHUB_ENV

    # 克隆代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 JDK 17 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    # 缓存 Maven 依赖
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Maven 构建
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t 这里填你的阿里云镜像:${{ env.SHORT_SHA }} .

    # 登录阿里云 Docker 仓库
    - name: Log in to Aliyun Docker Registry
      uses: docker/login-action@v2
      with:
        username: 阿里云用户名
        password: ${{ secrets.ALIYUN_PASSWORD }}
        registry: 你的阿里云仓库地址

    # 推送镜像到阿里云镜像仓库
    - name: Push Docker image to Aliyun Registry
      run: |
        docker tag 你的tag信息
        docker push 你的镜像信息

    # 通知服务器更新
    - name: Notify server to update Docker image
      run: |
        curl -k -X POST "这填你的webhook地址&param=${{ env.SHORT_SHA }}"
